name: Eleventy Build
on:
    push:
        branches:
            - main

jobs:
    build_deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Build
              uses: TartanLlama/actions-eleventy@master

            # - name: Deploy (Internal Branch)
            #   uses: peaceiris/actions-gh-pages@v3
            #   with:
            #       publish_dir: _site
            #       publish_branch: gh-pages
            #       github_token: ${{ secrets.REPO_ACCESS_TOKEN }}

            - name: Deploy (External Repo)
              uses: cpina/github-action-push-to-another-repository@main
              env:
                  API_TOKEN_GITHUB: ${{ secrets.REPO_ACCESS_TOKEN }}
              with:
                  source-directory: "_site"
                  destination-github-username: "col-lefevre"
                  destination-repository-name: "col-lefevre.github.io"
                  user-email: colin.lefevre.school@gmail.com
                  target-branch: main
