name: Eleventy Build and Deploy

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-22.04
        permissions:
            contents: write
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}
        steps:
            - uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: "18"

            - name: Persist npm cache
              uses: actions/cache@v3
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}

            - name: Persist Eleventy .cache
              uses: actions/cache@v3
              with:
                  path: ./.cache
                  key: ${{ runner.os }}-eleventy-fetch-cache

            - run: npm install
            - run: npm run build

            - name: Deploy (External Repo)
              uses: cpina/github-action-push-to-another-repository@main
              env:
                  API_TOKEN_GITHUB: ${{ secrets.REPO_ACCESS_TOKEN }}
              with:
                  source-directory: "_site"
                  destination-github-username: "col-lefevre"
                  destination-repository-name: "col-lefevre.github.io"
                  user-email: colin.lefevre.school@gmail.com
                  target-branch: main
